/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckConda: typeof import('./src/components/config/CheckConda.vue')['default']
    CheckCuda: typeof import('./src/components/config/CheckCuda.vue')['default']
    CheckPycharm: typeof import('./src/components/config/CheckPycharm.vue')['default']
    DefaultInstall: typeof import('./src/components/config/DefaultInstall.vue')['default']
    Drawer: typeof import('./src/components/config/base/Drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EnvDetail: typeof import('./src/components/envs/EnvDetail.vue')['default']
    EnvPage: typeof import('./src/components/envs/EnvPage.vue')['default']
    NaviBar: typeof import('./src/components/NaviBar.vue')['default']
    NewEnvDrawer: typeof import('./src/components/envs/NewEnvDrawer.vue')['default']
    OptionItem: typeof import('./src/components/config/base/OptionItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysConf: typeof import('./src/components/config/SysConf.vue')['default']
    UseGlobal: typeof import('./src/components/config/UseGlobal.vue')['default']
  }
}
